# Generated by Django 6.0.5 on 2026-05-16 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
                ('translation', models.TextField()),
                ('cefr_level', models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper-Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficient')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['word'],
                'indexes': [models.Index(fields=['cefr_level'], name='words_word_cefr_le_ee24da_idx'), models.Index(fields=['word'], name='words_word_word_a2cf21_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_count', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.word')),
            ],
            options={
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['user', 'word'], name='words_userw_user_id_d18ad7_idx'), models.Index(fields=['user', 'last_reviewed'], name='words_userw_user_id_8fb457_idx')],
                'unique_together': {('user', 'word')},
            },
        ),
    ]
