# Generated by Django 6.0.5 on 2026-05-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='context_paragraph',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='word',
            name='example_sentences',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='word',
            name='is_verb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='word',
            name='verb_forms',
            field=models.TextField(blank=True, default=''),
        ),
    ]
