# Generated by Django after removing the quiz feature.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizResult',
        ),
    ]
